# Copyright (c) 2026 LightSeek Foundation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Composable input generators for numerical correctness tests.

The package exports the stable public input-generator surface while keeping
core tensor primitives separate from op/layer-family generators.
"""

from __future__ import annotations

from tokenspeed_numerics_input_generators.activation import (
    FusedGateSigmoidMulAddInputConfig,
    FusedGateSigmoidMulAddInputs,
    FusedGateSigmoidMulAddInputValues,
    FusedSwiGLUFP8UE8M0InputConfig,
    FusedSwiGLUFP8UE8M0Inputs,
    FusedSwiGLUFP8UE8M0InputValues,
    GatedActivationInputConfig,
    GatedActivationInputs,
    GatedActivationInputValues,
    SigmoidMulInputConfig,
    SigmoidMulInputs,
    SigmoidMulInputValues,
)
from tokenspeed_numerics_input_generators.attention import (
    AttentionMergeStateInputConfig,
    AttentionMergeStateInputs,
    AttentionMergeStateInputValues,
    MHAInputConfig,
    MHAInputs,
    MHAInputValues,
    MLAInputConfig,
    MLAInputs,
    MLAInputValues,
    attention_merge_state_reference,
)
from tokenspeed_numerics_input_generators.attention_cache import (
    AttentionCacheInput,
    KVCacheInput,
    KVCacheInputConfig,
    KVCacheLayout,
    KVCacheValues,
    MLAKVCacheInput,
    MLAKVCacheInputConfig,
    MLAKVCacheValues,
    PageTableInput,
    PageTableInputConfig,
    PageTableValues,
)
from tokenspeed_numerics_input_generators.attention_metadata import (
    MHARequestMetadataInputConfig,
    MHARequestMetadataInput,
    MHARequestMetadataValues,
)
from tokenspeed_numerics_input_generators.communication import (
    AllGatherInputConfig,
    AllGatherInputs,
    AllGatherInputValues,
    AllReduceResidualRMSNormInputConfig,
    AllReduceResidualRMSNormInputs,
    AllReduceResidualRMSNormInputValues,
    AllReduceResidualRMSNormReferenceValues,
    AllReduceInputConfig,
    AllReduceInputs,
    AllReduceInputValues,
    ReduceScatterInputConfig,
    ReduceScatterInputs,
    ReduceScatterInputValues,
    all_gather_reference,
    all_reduce_residual_rmsnorm_reference,
    all_reduce_sum_reference,
    reduce_scatter_sum_reference,
)
from tokenspeed_numerics_input_generators.core import (
    CustomDType,
    DeviceLike,
    InputDType,
    NumericsInputGenerator,
    TensorInput,
    TensorValues,
)
from tokenspeed_numerics_input_generators.embedding import (
    RopeFusedKVInputValues,
    RopeInputConfig,
    RopeInputValues,
    RopeInputs,
    rope_reference,
)
from tokenspeed_numerics_input_generators.gemm import (
    GemmInputConfig,
    GemmInputValues,
    GemmInputs,
    gemm_scale_shape,
    mxfp4_gemm_input_config,
)
from tokenspeed_numerics_input_generators.kvcache import (
    FP8KVCacheWriteInputConfig,
    FP8KVCacheWriteInputs,
    FP8KVCacheWriteInputValues,
    KVCacheStoreInputConfig,
    KVCacheStoreInputs,
    KVCacheStoreInputValues,
    KVCacheTransferInputConfig,
    KVCacheTransferInputs,
    KVCacheTransferInputValues,
    MLAKVCacheTransferInputConfig,
    MLAKVCacheTransferInputs,
    MLAKVCacheTransferInputValues,
    PageTableGatherInputConfig,
    PageTableGatherInputs,
    PageTableGatherInputValues,
    fp8_kv_cache_write_reference,
    kv_cache_store_reference,
    kv_cache_transfer_reference,
    mla_kv_cache_transfer_reference,
    page_table_gather_reference,
)
from tokenspeed_numerics_input_generators.layernorm import (
    FusedQKRMSNormRopeGateInputConfig,
    FusedQKRMSNormRopeGateInputs,
    FusedQKRMSNormRopeGateInputValues,
    ParallelRMSNormInputConfig,
    ParallelRMSNormInputs,
    ParallelRMSNormInputValues,
    QKRMSNormInputConfig,
    QKRMSNormInputs,
    QKRMSNormInputValues,
    RMSNormInputConfig,
    RMSNormInputs,
    RMSNormInputValues,
    fused_qk_rmsnorm_rope_gate_reference,
    qk_rmsnorm_reference,
    rmsnorm_reference,
)
from tokenspeed_numerics_input_generators.moe import (
    MoeAlignBlockSizeInputConfig,
    MoeAlignBlockSizeInputs,
    MoeAlignBlockSizeInputValues,
    MoeAlignBlockSizeReferenceValues,
    MoeInputConfig,
    MoeInputs,
    MoeInputValues,
    canonicalize_moe_align_block_size,
    moe_align_block_size_buffer_dims,
    moe_align_block_size_reference,
)
from tokenspeed_numerics_input_generators.quantization import (
    FP8QuantizationInputConfig,
    FP8QuantizationInputs,
    FP8QuantizationInputValues,
    MXFP8QuantizationInputConfig,
    MXFP8QuantizationInputs,
    MXFP8QuantizationInputValues,
    MXFP4QuantizationInputConfig,
    MXFP4QuantizationInputs,
    MXFP4QuantizationInputValues,
    NVFP4QuantizationInputConfig,
    NVFP4QuantizationInputs,
    NVFP4QuantizationInputValues,
    fp8_quantization_reference,
    fp8_scale_shape,
    mxfp4_quantization_reference,
    mxfp4_scale_shape,
    mxfp8_quantization_reference,
    mxfp8_scale_shape,
    nvfp4_quantization_reference,
    nvfp4_scale_shape,
)
from tokenspeed_numerics_input_generators.rotary import build_rope_cos_sin_cache
from tokenspeed_numerics_input_generators.sampling import (
    ArgmaxInputConfig,
    ArgmaxInputs,
    ArgmaxInputValues,
    ArgmaxPairInputConfig,
    ArgmaxPairInputs,
    ArgmaxPairInputValues,
    GatherExpandScalarsInputConfig,
    GatherExpandScalarsInputs,
    GatherExpandScalarsInputValues,
    MinPRenormInputConfig,
    MinPRenormInputs,
    MinPRenormInputValues,
    TopKTopPRenormInputConfig,
    TopKTopPRenormInputs,
    TopKTopPRenormInputValues,
    argmax_pair_reference,
    argmax_reference,
    gather_expand_scalars_reference,
    min_p_renorm_reference,
    top_k_top_p_renorm_reference,
)

__all__ = [
    "AllGatherInputConfig",
    "AllGatherInputValues",
    "AllGatherInputs",
    "AllReduceInputConfig",
    "AllReduceInputValues",
    "AllReduceInputs",
    "AllReduceResidualRMSNormInputConfig",
    "AllReduceResidualRMSNormInputValues",
    "AllReduceResidualRMSNormInputs",
    "AllReduceResidualRMSNormReferenceValues",
    "AttentionMergeStateInputConfig",
    "AttentionMergeStateInputValues",
    "AttentionMergeStateInputs",
    "ArgmaxInputConfig",
    "ArgmaxInputValues",
    "ArgmaxInputs",
    "ArgmaxPairInputConfig",
    "ArgmaxPairInputValues",
    "ArgmaxPairInputs",
    "AttentionCacheInput",
    "CustomDType",
    "DeviceLike",
    "FusedGateSigmoidMulAddInputConfig",
    "FusedGateSigmoidMulAddInputValues",
    "FusedGateSigmoidMulAddInputs",
    "FusedSwiGLUFP8UE8M0InputConfig",
    "FusedSwiGLUFP8UE8M0InputValues",
    "FusedSwiGLUFP8UE8M0Inputs",
    "FP8KVCacheWriteInputConfig",
    "FP8KVCacheWriteInputValues",
    "FP8KVCacheWriteInputs",
    "FP8QuantizationInputConfig",
    "FP8QuantizationInputValues",
    "FP8QuantizationInputs",
    "FusedQKRMSNormRopeGateInputConfig",
    "FusedQKRMSNormRopeGateInputValues",
    "FusedQKRMSNormRopeGateInputs",
    "GatherExpandScalarsInputConfig",
    "GatherExpandScalarsInputValues",
    "GatherExpandScalarsInputs",
    "GemmInputConfig",
    "GemmInputValues",
    "GemmInputs",
    "GatedActivationInputConfig",
    "GatedActivationInputValues",
    "GatedActivationInputs",
    "InputDType",
    "KVCacheInput",
    "KVCacheInputConfig",
    "KVCacheLayout",
    "KVCacheStoreInputConfig",
    "KVCacheStoreInputValues",
    "KVCacheStoreInputs",
    "KVCacheTransferInputConfig",
    "KVCacheTransferInputValues",
    "KVCacheTransferInputs",
    "KVCacheValues",
    "MHAInputConfig",
    "MHAInputValues",
    "MHAInputs",
    "MLAInputConfig",
    "MLAInputValues",
    "MLAInputs",
    "MLAKVCacheInput",
    "MLAKVCacheInputConfig",
    "MLAKVCacheTransferInputConfig",
    "MLAKVCacheTransferInputValues",
    "MLAKVCacheTransferInputs",
    "MLAKVCacheValues",
    "MHARequestMetadataInputConfig",
    "MHARequestMetadataInput",
    "MHARequestMetadataValues",
    "MinPRenormInputConfig",
    "MinPRenormInputValues",
    "MinPRenormInputs",
    "MoeAlignBlockSizeInputConfig",
    "MoeAlignBlockSizeInputValues",
    "MoeAlignBlockSizeInputs",
    "MoeAlignBlockSizeReferenceValues",
    "MoeInputConfig",
    "MoeInputValues",
    "MoeInputs",
    "MXFP4QuantizationInputConfig",
    "MXFP4QuantizationInputValues",
    "MXFP4QuantizationInputs",
    "MXFP8QuantizationInputConfig",
    "MXFP8QuantizationInputValues",
    "MXFP8QuantizationInputs",
    "NVFP4QuantizationInputConfig",
    "NVFP4QuantizationInputValues",
    "NVFP4QuantizationInputs",
    "NumericsInputGenerator",
    "PageTableInput",
    "PageTableGatherInputConfig",
    "PageTableGatherInputValues",
    "PageTableGatherInputs",
    "PageTableInputConfig",
    "PageTableValues",
    "ParallelRMSNormInputConfig",
    "ParallelRMSNormInputValues",
    "ParallelRMSNormInputs",
    "QKRMSNormInputConfig",
    "QKRMSNormInputValues",
    "QKRMSNormInputs",
    "ReduceScatterInputConfig",
    "ReduceScatterInputValues",
    "ReduceScatterInputs",
    "RMSNormInputConfig",
    "RMSNormInputValues",
    "RMSNormInputs",
    "RopeFusedKVInputValues",
    "RopeInputConfig",
    "RopeInputValues",
    "RopeInputs",
    "SigmoidMulInputConfig",
    "SigmoidMulInputValues",
    "SigmoidMulInputs",
    "TensorInput",
    "TensorValues",
    "TopKTopPRenormInputConfig",
    "TopKTopPRenormInputValues",
    "TopKTopPRenormInputs",
    "argmax_reference",
    "all_gather_reference",
    "all_reduce_residual_rmsnorm_reference",
    "all_reduce_sum_reference",
    "argmax_pair_reference",
    "attention_merge_state_reference",
    "build_rope_cos_sin_cache",
    "canonicalize_moe_align_block_size",
    "fp8_quantization_reference",
    "fp8_kv_cache_write_reference",
    "fp8_scale_shape",
    "fused_qk_rmsnorm_rope_gate_reference",
    "gather_expand_scalars_reference",
    "gemm_scale_shape",
    "kv_cache_store_reference",
    "kv_cache_transfer_reference",
    "min_p_renorm_reference",
    "mla_kv_cache_transfer_reference",
    "moe_align_block_size_buffer_dims",
    "moe_align_block_size_reference",
    "mxfp4_gemm_input_config",
    "mxfp4_quantization_reference",
    "mxfp4_scale_shape",
    "mxfp8_quantization_reference",
    "mxfp8_scale_shape",
    "nvfp4_quantization_reference",
    "nvfp4_scale_shape",
    "qk_rmsnorm_reference",
    "page_table_gather_reference",
    "reduce_scatter_sum_reference",
    "rope_reference",
    "rmsnorm_reference",
    "top_k_top_p_renorm_reference",
]
