#!/usr/bin/env python3
"""Validate production TokenSpeed GLM DSA scoring on the full 24-cell grid.

The validator consumes the neutral NumPy fixture generated by
``benchmark_dsa_scoring.py generate``. Its PyTorch reference is deliberately
independent of TokenSpeed: it decodes the serialized BF16/FP8 bit patterns,
dequantizes each key row, performs FP32 dot products, applies per-head ReLU,
then reduces with signed FP32 weights. Reference work is bounded by
``--chunk-rows`` so the million-token prefill cases do not need a full
per-head score tensor.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import math
import os
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

FIXTURE_SCHEMA = "tokenspeed.dsa-scoring-fixture.v1"
REPORT_SCHEMA = "tokenspeed.dsa-scoring-correctness.v1"
SEQ_LENS = (
    512,
    1024,
    2048,
    8192,
    16384,
    32768,
    65536,
    90000,
    131072,
    262144,
    524288,
    1048576,
)
MODES = ("decode", "prefill")
NUM_HEADS = 32
HEAD_DIM = 128
PAGE_SIZE = 64
ROW_BYTES = HEAD_DIM + 4
PREFILL_ROWS = 64
SOFTMAX_SCALE = HEAD_DIM**-0.5
DEFAULT_CHUNK_ROWS = 8192

REQUIRED_ARRAYS = {
    "decode_q_bf16_bits": ("uint16", (1, NUM_HEADS, HEAD_DIM)),
    "decode_weights_f32": ("float32", (1, NUM_HEADS)),
    "prefill_q_bf16_bits": ("uint16", (PREFILL_ROWS, NUM_HEADS, HEAD_DIM)),
    "prefill_weights_f32": ("float32", (PREFILL_ROWS, NUM_HEADS)),
    "key_e4m3fn_bits": ("uint8", (max(SEQ_LENS), HEAD_DIM)),
    "key_scale_f32": ("float32", (max(SEQ_LENS),)),
}


def _utc_now() -> str:
    return dt.datetime.now(dt.UTC).isoformat()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _canonical_hash(payload: Any) -> str:
    encoded = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _load_manifest(fixture_dir: Path) -> dict[str, Any]:
    manifest_path = fixture_dir / "manifest.json"
    with manifest_path.open(encoding="utf-8") as stream:
        manifest = json.load(stream)
    if manifest.get("schema") != FIXTURE_SCHEMA:
        raise ValueError(
            f"unsupported fixture schema {manifest.get('schema')!r} in {manifest_path}"
        )
    expected_metadata = {
        "seq_lens": list(SEQ_LENS),
        "num_heads": NUM_HEADS,
        "head_dim": HEAD_DIM,
        "page_size": PAGE_SIZE,
        "prefill_rows": PREFILL_ROWS,
    }
    for field, expected in expected_metadata.items():
        if manifest.get(field) != expected:
            raise ValueError(
                f"fixture {field} mismatch: expected {expected!r}, "
                f"got {manifest.get(field)!r}"
            )
    semantics = manifest.get("semantics", {})
    expected_semantics = {
        "query_source_dtype": "bfloat16",
        "weights_dtype": "float32_signed",
        "key_dtype": "float8_e4m3fn",
        "key_scale_dtype": "float32_per_row",
        "key_dequantization": "key_e4m3fn * key_scale_f32",
        "softmax_scale": SOFTMAX_SCALE,
    }
    for field, expected in expected_semantics.items():
        if semantics.get(field) != expected:
            raise ValueError(
                f"fixture semantic {field} mismatch: expected {expected!r}, "
                f"got {semantics.get(field)!r}"
            )
    arrays = manifest.get("arrays", {})
    for logical_name, metadata in arrays.items():
        path = fixture_dir / metadata["filename"]
        actual_sha256 = _sha256_file(path)
        if actual_sha256 != metadata.get("sha256"):
            raise ValueError(
                f"fixture checksum mismatch for {logical_name}: expected "
                f"{metadata.get('sha256')}, got {actual_sha256}"
            )
    for logical_name, (dtype, shape) in REQUIRED_ARRAYS.items():
        metadata = arrays.get(logical_name)
        if metadata is None:
            raise ValueError(f"fixture is missing {logical_name}")
        if metadata.get("dtype") != dtype or metadata.get("shape") != list(shape):
            raise ValueError(
                f"fixture {logical_name} metadata mismatch: expected "
                f"dtype={dtype} shape={list(shape)}, got {metadata}"
            )
    identity_payload = {
        field: manifest[field]
        for field in (
            "schema",
            "seed",
            "seq_lens",
            "num_heads",
            "head_dim",
            "page_size",
            "prefill_rows",
            "q_std",
            "key_std",
            "arrays",
        )
    }
    actual_fixture_id = _canonical_hash(identity_payload)
    if manifest.get("fixture_id") != actual_fixture_id:
        raise ValueError(
            "fixture identity mismatch: expected "
            f"{actual_fixture_id}, got {manifest.get('fixture_id')}"
        )
    return manifest


def _require_single_visible_gpu() -> dict[str, str]:
    visibility = {
        name: os.environ[name]
        for name in ("ROCR_VISIBLE_DEVICES", "HIP_VISIBLE_DEVICES")
        if os.environ.get(name)
    }
    if not visibility:
        raise RuntimeError(
            "set ROCR_VISIBLE_DEVICES or HIP_VISIBLE_DEVICES to one idle GPU"
        )
    for name, value in visibility.items():
        if "," in value:
            raise RuntimeError(f"{name} must select exactly one GPU, got {value!r}")
    if len(set(visibility.values())) != 1:
        raise RuntimeError(f"GPU visibility variables disagree: {visibility}")
    return visibility


def _load_array(
    fixture_dir: Path,
    manifest: dict[str, Any],
    logical_name: str,
    *,
    device: Any,
) -> Any:
    import numpy as np
    import torch

    metadata = manifest["arrays"][logical_name]
    source = np.load(
        fixture_dir / metadata["filename"], mmap_mode="r", allow_pickle=False
    )
    host = torch.from_numpy(np.array(source, copy=True))
    return host.to(device=device, non_blocking=False)


def _load_fixture_tensors(
    fixture_dir: Path,
    manifest: dict[str, Any],
    *,
    device: Any,
) -> tuple[dict[str, tuple[Any, Any]], Any, Any]:
    import torch

    mode_inputs = {}
    for mode in MODES:
        q_bits = _load_array(
            fixture_dir,
            manifest,
            f"{mode}_q_bf16_bits",
            device=device,
        )
        q = q_bits.view(torch.bfloat16).contiguous()
        weights = _load_array(
            fixture_dir,
            manifest,
            f"{mode}_weights_f32",
            device=device,
        ).contiguous()
        if q.dtype != torch.bfloat16 or weights.dtype != torch.float32:
            raise TypeError(
                f"invalid {mode} dtypes: q={q.dtype}, weights={weights.dtype}"
            )
        if not bool((weights < 0).any()) or not bool((weights > 0).any()):
            raise ValueError(f"{mode} fixture weights must contain both signs")
        mode_inputs[mode] = (q, weights)

    key_bits = _load_array(
        fixture_dir,
        manifest,
        "key_e4m3fn_bits",
        device=device,
    )
    key_fp8 = key_bits.view(torch.float8_e4m3fn).contiguous()
    key_scales = _load_array(
        fixture_dir,
        manifest,
        "key_scale_f32",
        device=device,
    ).contiguous()
    if not bool(torch.isfinite(key_scales).all()) or not bool((key_scales > 0).all()):
        raise ValueError("fixture key scales must be finite and positive")
    return mode_inputs, key_fp8, key_scales


def _pack_production_cache(key_fp8: Any, key_scales: Any) -> Any:
    import torch

    num_slots = int(key_fp8.shape[0])
    if num_slots % PAGE_SIZE:
        raise ValueError(f"packed cache requires page-aligned slots, got {num_slots}")
    num_pages = num_slots // PAGE_SIZE
    packed = torch.empty(
        (num_slots, ROW_BYTES), dtype=torch.uint8, device=key_fp8.device
    )
    flat = packed.reshape(-1)
    page_bytes = PAGE_SIZE * ROW_BYTES
    fp8_view = torch.as_strided(
        flat.view(torch.float8_e4m3fn),
        (num_pages, PAGE_SIZE, HEAD_DIM),
        (page_bytes, HEAD_DIM, 1),
    )
    scale_view = torch.as_strided(
        flat.view(torch.float32),
        (num_pages, PAGE_SIZE, 1),
        (page_bytes // 4, 1, 1),
        (PAGE_SIZE * HEAD_DIM) // 4,
    )
    fp8_view.copy_(key_fp8.reshape(num_pages, PAGE_SIZE, HEAD_DIM))
    scale_view.copy_(key_scales.reshape(num_pages, PAGE_SIZE, 1))
    return packed


def _production_cell(
    mode: str,
    seq_len: int,
    q: Any,
    weights: Any,
    packed_cache: Any,
) -> tuple[Any, Any]:
    import torch
    from tokenspeed_kernel_amd.ops.attention.gluon.dsa_topk_gfx950 import (
        _launch_dsa_decode_logits_fp8,
        _launch_dsa_prefill_logits_fp8,
    )

    if mode == "decode":
        allocated_seq_len = math.ceil(seq_len / PAGE_SIZE) * PAGE_SIZE
        num_pages = allocated_seq_len // PAGE_SIZE
        seq_lens = torch.tensor([seq_len], dtype=torch.int32, device=q.device)
        block_table = torch.arange(
            num_pages, dtype=torch.int32, device=q.device
        ).reshape(1, num_pages)
        logits = torch.empty(
            (1, allocated_seq_len), dtype=torch.float32, device=q.device
        )

        def launch() -> None:
            _launch_dsa_decode_logits_fp8(
                q,
                packed_cache,
                weights,
                seq_lens,
                block_table,
                logits,
                page_size=PAGE_SIZE,
                row_bytes=ROW_BYTES,
                softmax_scale=SOFTMAX_SCALE,
                q_len_per_req=1,
            )

        return launch, logits

    workspace_slots = torch.arange(seq_len, dtype=torch.int64, device=q.device)
    row_starts = torch.zeros(PREFILL_ROWS, dtype=torch.int32, device=q.device)
    row_ends = torch.arange(
        seq_len - PREFILL_ROWS + 1,
        seq_len + 1,
        dtype=torch.int32,
        device=q.device,
    )
    logits = torch.empty((PREFILL_ROWS, seq_len), dtype=torch.float32, device=q.device)

    def launch() -> None:
        _launch_dsa_prefill_logits_fp8(
            q,
            packed_cache,
            weights,
            workspace_slots,
            row_starts,
            row_ends,
            logits,
            page_size=PAGE_SIZE,
            row_bytes=ROW_BYTES,
            softmax_scale=SOFTMAX_SCALE,
        )

    return launch, logits


def _reference_scores(
    query_columns: Any,
    weights: Any,
    key_fp8: Any,
    key_scales: Any,
    start: int,
    end: int,
) -> Any:
    keys = key_fp8[start:end].float()
    keys.mul_(key_scales[start:end, None])
    per_head = keys @ query_columns
    per_head.clamp_min_(0.0)
    rows = int(weights.shape[0])
    per_head = per_head.reshape(end - start, rows, NUM_HEADS)
    per_head.mul_(weights[None, :, :])
    return (per_head.sum(dim=2) * SOFTMAX_SCALE).transpose(0, 1)


def _validate_cell(
    mode: str,
    seq_len: int,
    q: Any,
    weights: Any,
    key_fp8: Any,
    key_scales: Any,
    packed_cache: Any,
    *,
    chunk_rows: int,
    rtol: float,
    atol: float,
) -> dict[str, Any]:
    import torch

    launch, logits = _production_cell(mode, seq_len, q, weights, packed_cache)
    launch()
    torch.cuda.synchronize()
    query_columns = (
        q.float().reshape(q.shape[0] * NUM_HEADS, HEAD_DIM).transpose(0, 1)
    ).contiguous()
    if mode == "decode":
        row_ends = torch.tensor([seq_len], dtype=torch.int64, device=q.device)
    else:
        row_ends = torch.arange(
            seq_len - PREFILL_ROWS + 1,
            seq_len + 1,
            dtype=torch.int64,
            device=q.device,
        )

    mask_mismatches = 0
    value_mismatches = 0
    max_abs_error = 0.0
    max_rel_error = 0.0
    output_cols = int(logits.shape[1])
    for start in range(0, output_cols, chunk_rows):
        end = min(start + chunk_rows, output_cols)
        actual = logits[:, start:end]
        positions = torch.arange(start, end, dtype=torch.int64, device=q.device)
        valid = positions[None, :] < row_ends[:, None]
        expected_neg_inf = ~valid
        mask_mismatches += int(
            (torch.isneginf(actual) != expected_neg_inf).sum().item()
        )
        reference = _reference_scores(
            query_columns,
            weights,
            key_fp8,
            key_scales,
            start,
            end,
        )
        actual_values = actual[valid]
        reference_values = reference[valid]
        if actual_values.numel() == 0:
            continue
        close = torch.isclose(actual_values, reference_values, rtol=rtol, atol=atol)
        value_mismatches += int((~close).sum().item())
        finite = torch.isfinite(actual_values) & torch.isfinite(reference_values)
        if bool(finite.any()):
            absolute_error = (actual_values[finite] - reference_values[finite]).abs()
            relative_error = absolute_error / reference_values[finite].abs().clamp_min(
                1.0e-12
            )
            max_abs_error = max(max_abs_error, float(absolute_error.max().item()))
            max_rel_error = max(max_rel_error, float(relative_error.max().item()))

    passed = mask_mismatches == 0 and value_mismatches == 0
    return {
        "cell_id": f"{mode}:{seq_len}",
        "mode": mode,
        "seq_len": seq_len,
        "q_shape": list(q.shape),
        "weights_shape": list(weights.shape),
        "output_shape": list(logits.shape),
        "passed": passed,
        "mask_mismatches": mask_mismatches,
        "value_mismatches": value_mismatches,
        "max_abs_error": max_abs_error,
        "max_rel_error": max_rel_error,
    }


def _write_report(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    with temporary.open("w", encoding="utf-8") as stream:
        json.dump(payload, stream, indent=2, sort_keys=True)
        stream.write("\n")
    os.replace(temporary, path)


def _run(args: argparse.Namespace) -> None:
    import torch

    if args.chunk_rows <= 0:
        raise ValueError("--chunk-rows must be positive")
    if args.rtol < 0 or args.atol < 0:
        raise ValueError("--rtol and --atol must be nonnegative")
    visibility = _require_single_visible_gpu()
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA/HIP device is required")
    device = torch.device(args.device)
    torch.cuda.set_device(device)
    properties = torch.cuda.get_device_properties(torch.cuda.current_device())
    arch = getattr(properties, "gcnArchName", "")
    if "gfx950" not in arch:
        raise RuntimeError(f"GFX950 is required, got {arch or properties.name}")

    fixture_dir = args.fixture_dir.resolve()
    manifest = _load_manifest(fixture_dir)
    mode_inputs, key_fp8, key_scales = _load_fixture_tensors(
        fixture_dir, manifest, device=device
    )
    packed_cache = _pack_production_cache(key_fp8, key_scales)
    results = []
    started_at = _utc_now()
    with torch.inference_mode():
        for seq_len in SEQ_LENS:
            for mode in MODES:
                q, weights = mode_inputs[mode]
                try:
                    result = _validate_cell(
                        mode,
                        seq_len,
                        q,
                        weights,
                        key_fp8,
                        key_scales,
                        packed_cache,
                        chunk_rows=args.chunk_rows,
                        rtol=args.rtol,
                        atol=args.atol,
                    )
                except Exception as error:  # Keep checking the remaining grid.
                    result = {
                        "cell_id": f"{mode}:{seq_len}",
                        "mode": mode,
                        "seq_len": seq_len,
                        "q_shape": list(q.shape),
                        "weights_shape": list(weights.shape),
                        "passed": False,
                        "error": f"{type(error).__name__}: {error}",
                    }
                results.append(result)
                status = "PASS" if result["passed"] else "FAIL"
                print(f"{status} {result['cell_id']}", file=sys.stderr, flush=True)
                torch.cuda.empty_cache()

    passed = len(results) == 24 and all(result["passed"] for result in results)
    payload = {
        "schema": REPORT_SCHEMA,
        "created_at_utc": _utc_now(),
        "started_at_utc": started_at,
        "fixture_id": manifest["fixture_id"],
        "fixture_manifest_sha256": _sha256_file(fixture_dir / "manifest.json"),
        "grid": {
            "modes": list(MODES),
            "seq_lens": list(SEQ_LENS),
            "cell_count": 24,
        },
        "reference": {
            "query_dtype": "bfloat16_converted_to_float32",
            "key_dtype": "float8_e4m3fn_dequantized_to_float32_per_chunk",
            "key_scale_dtype": "float32_per_row",
            "dot_accumulation": "pytorch_float32_matmul",
            "activation": "per_head_relu_before_signed_weight_reduction",
            "weights_dtype": "float32_signed",
            "softmax_scale": SOFTMAX_SCALE,
            "chunk_rows": args.chunk_rows,
            "rtol": args.rtol,
            "atol": args.atol,
            "mask": "exact_negative_infinity",
        },
        "production": {
            "scorer": "tokenspeed_preallocated_gluon_score_launchers",
            "query_dtype": "bfloat16",
            "key_layout": "page64_packed_fp8_plus_per_row_fp32_scale",
            "decode_page_table": "identity_pages",
            "prefill_workspace": "identity_slots_causal_row_ends",
        },
        "environment": {
            "torch": torch.__version__,
            "hip": getattr(torch.version, "hip", None),
            "device_name": properties.name,
            "device_arch": arch,
            "gpu_visibility": visibility,
        },
        "passed": passed,
        "passed_cells": sum(result["passed"] for result in results),
        "results": results,
    }
    _write_report(args.output.resolve(), payload)
    print(json.dumps(payload, indent=2, sort_keys=True))
    if not passed:
        raise SystemExit(1)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture-dir",
        type=Path,
        default=Path("benchmark-results/dsa_score_aiter/fixture"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("benchmark-results/dsa_score_aiter/correctness.json"),
    )
    parser.add_argument("--chunk-rows", type=int, default=DEFAULT_CHUNK_ROWS)
    parser.add_argument("--rtol", type=float, default=3.0e-3)
    parser.add_argument("--atol", type=float, default=3.0e-4)
    parser.add_argument("--device", default="cuda:0")
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    args = _build_parser().parse_args(argv)
    _run(args)


if __name__ == "__main__":
    main()
